
keyList =[
    "title_url",
    "entities",
    "spacy_entities",
    "sentence_id", 
    "lines_per_sentence", 
    "sentences",
    "sentence_sentiment_compound",
    "sentence_sentiment_neg",
    "sentence_sentiment_neu",
    "sentence_sentiment_pos",
    # "spacy_tokens",
    "avg_tokens_sentence",
    # "unique_words",
    "last_word_per_line",
    # "common_bigrams",
    "most_common_words",
    "poetic_form",
    "perc_poetry_syllables",
    "perc_poetry_rhymes",
    "perc_drama",
    "places",
    "orgs",
    "summary",
    # "lemmatized_words",
    "internal_rhyme_most_recent",
    # "internal_rhyme_second_most_recent",
    ]
fullKeyList =[
    "title_url",
    "entities",
    "spacy_entities",
    "sentence_id", 
    "lines_per_sentence", 
    "sentences",
    "sentence_sentiment_compound",
    "sentence_sentiment_neg",
    "sentence_sentiment_neu",
    "sentence_sentiment_pos",
    # "spacy_tokens",
    "avg_tokens_sentence",
    # "unique_words",
    "last_word_per_line",
    # "common_bigrams",
    "most_common_words",
    "poetic_form",
    "perc_poetry_syllables",
    "perc_poetry_rhymes",
    "perc_drama",
    "places",
    "orgs",
    "summary",
    # "lemmatized_words",
    "internal_rhyme_most_recent",
    # "internal_rhyme_second_most_recent",
    "old_df_vectorized_features",
    "old_df_vectorized_vocab",
    "old_df_vectorized_tfidf",
    "old_df_euclidean_distance_since_last_self"
]
